#training or simulation
mode: training
cprofile: true

training:
  instances: 5
  pool_size: -1 #-1 for all threads, 0 for no threads, n for n threads
  headless: true
  agent_count: 20
  sensor_count: 6
  sensor_max_distance: 100

#  model:
    #BRAIN_SIZE_INPUT, BRAIN_SIZE_HIDDEN, BRAIN_SIZE_HIDDEN, BRAIN_SIZE_OUTPUT],'relu'


